site_name: Custom Event Communication
site_description: Provides a more flexible way of sending emails to event participant.
site_author: SYSTOPIA
repo_url: https://github.com/systopia/de.systopia.eventmessages

theme:
  name: material

nav:
  - Introduction: index.md
  - Configuration: configuration.md
  - Usage: usage.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
